
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace MLNETExamples.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.ReadKey();
        }
    }
}
