// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MLNETExamples.ConsoleApp
{
    public partial class Restaurant
    {
        /// <summary>
        /// model input class for Restaurant.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"alternate")]
            public float Alternate { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"bar")]
            public float Bar { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"fri/sat")]
            public float Fri_sat { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"hungry")]
            public float Hungry { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"patrons")]
            public float Patrons { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"price")]
            public float Price { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"raining")]
            public float Raining { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"reservation")]
            public float Reservation { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"type")]
            public float Type { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"wait_estimate")]
            public float Wait_estimate { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"will_wait")]
            public float Will_wait { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for Restaurant.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"alternate")]
            public float Alternate { get; set; }

            [ColumnName(@"bar")]
            public float Bar { get; set; }

            [ColumnName(@"fri/sat")]
            public float Fri_sat { get; set; }

            [ColumnName(@"hungry")]
            public float Hungry { get; set; }

            [ColumnName(@"patrons")]
            public float Patrons { get; set; }

            [ColumnName(@"price")]
            public float Price { get; set; }

            [ColumnName(@"raining")]
            public float Raining { get; set; }

            [ColumnName(@"reservation")]
            public float Reservation { get; set; }

            [ColumnName(@"type")]
            public float Type { get; set; }

            [ColumnName(@"wait_estimate")]
            public float Wait_estimate { get; set; }

            [ColumnName(@"will_wait")]
            public uint Will_wait { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        public static string MLNetModelPath = Path.GetFullPath("Restaurant.mlnet");
        public static string MLNetCompleteModelPath = Path.GetFullPath("RestaurantComplete.mlnet");
        public static string MLNet5xModelPath = Path.GetFullPath("Restaurant5x.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict scores for all possible labels.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static IOrderedEnumerable<KeyValuePair<string, float>> PredictAllLabels(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            var result = predEngine.Predict(input);
            return GetSortedScoresWithLabels(result);
        }

        /// <summary>
        /// Map the unlabeled result score array to the predicted label names.
        /// </summary>
        /// <param name="result">Prediction to get the labeled scores from.</param>
        /// <returns>Ordered list of label and score.</returns>
        /// <exception cref="Exception"></exception>
        public static IOrderedEnumerable<KeyValuePair<string, float>> GetSortedScoresWithLabels(ModelOutput result)
        {
            var unlabeledScores = result.Score;
            var labelNames = GetLabels(result);

            Dictionary<string, float> labledScores = new Dictionary<string, float>();
            for (int i = 0; i < labelNames.Count(); i++)
            {
                // Map the names to the predicted result score array
                var labelName = labelNames.ElementAt(i);
                labledScores.Add(labelName.ToString(), unlabeledScores[i]);
            }

            return labledScores.OrderByDescending(c => c.Value);
        }

        /// <summary>
        /// Get the ordered label names.
        /// </summary>
        /// <param name="result">Predicted result to get the labels from.</param>
        /// <returns>List of labels.</returns>
        /// <exception cref="Exception"></exception>
        private static IEnumerable<string> GetLabels(ModelOutput result)
        {
            var schema = PredictEngine.Value.OutputSchema;

            var labelColumn = schema.GetColumnOrNull("will_wait");
            if (labelColumn == null)
            {
                throw new Exception("will_wait column not found. Make sure the name searched for matches the name in the schema.");
            }

            // Key values contains an ordered array of the possible labels. This allows us to map the results to the correct label value.
            var keyNames = new VBuffer<float>();
            labelColumn.Value.GetKeyValues(ref keyNames);
            return keyNames.DenseValues().Select(x => x.ToString());
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
